name: Auto-update completion status based on due date

on:
  schedule:
    - cron: "0 3 * * *" # runs daily at 3 AM UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run automation logic
        env:
          ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
          ORG: aantorika-6simplex
          PROJECT_NUMBER: 1
        run: |
          npm install graphql-request dayjs

          cat <<'EOF' > script.js
          import { GraphQLClient, gql } from "graphql-request";
          import dayjs from "dayjs";

          // === CONFIGURATION ===
          const client = new GraphQLClient("https://api.github.com/graphql", {
            headers: { Authorization: `Bearer ${process.env.ACTION_TOKEN}` },
          });

          const login = process.env.ORG;
          const projectNumber = parseInt(process.env.PROJECT_NUMBER);

          // === PROJECT FIELD CONSTANTS ===
          const projectId = "PVT_kwHODWXJGc4BGnXt";
          const completionStatusFieldId = "PVTSSF_lAHODWXJGc4BGnXtzg3nBFw"; // Completion Status
          const daysDelayedFieldId = "PVTF_lAHODWXJGc4BGnXtzg3nA9E";       // Days Delayed (Number)
          const daysBeforeFieldId = "PVTF_lAHODWXJGc4BGnXtzg3nFlU";        // Days Before (Number)

          // Single select option IDs for Completion Status
          const completionMap = {
            "On Due Date": "a4b55684",
            "Before Due Date": "739f8394",
            "Delayed": "23e776a7"
          };

          // === QUERIES ===
          const GET_ITEMS = gql`
            query($login: String!, $number: Int!) {
              user(login: $login) {
                projectV2(number: $number) {
                  id
                  items(first: 100) {
                    nodes {
                      id
                      fieldValues(first: 30) {
                        nodes {
                          ... on ProjectV2ItemFieldDateValue {
                            field { name id }
                            date
                          }
                          ... on ProjectV2ItemFieldNumberValue {
                            field { name id }
                            number
                          }
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            field { name id }
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          `;

          const UPDATE_SINGLE_SELECT = gql`
            mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $projectId
                  itemId: $itemId
                  fieldId: $fieldId
                  value: { singleSelectOptionId: $optionId }
                }
              ) {
                projectV2Item { id }
              }
            }
          `;

          const UPDATE_NUMBER = gql`
            mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $number: Float!) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $projectId
                  itemId: $itemId
                  fieldId: $fieldId
                  value: { number: $number }
                }
              ) {
                projectV2Item { id }
              }
            }
          `;

          // === MAIN LOGIC ===
          (async () => {
            try {
              const data = await client.request(GET_ITEMS, { login, number: projectNumber });
              const items = data.user.projectV2.items.nodes;
              const today = dayjs().startOf("day");

              console.log(`Found ${items.length} project items`);

              for (const item of items) {
                let status = "";
                let dueDate = "";

                for (const field of item.fieldValues.nodes) {
                  if (field.field?.name.toLowerCase() === "status") status = field.name;
                  if (field.field?.name.toLowerCase() === "due date") dueDate = field.date;
                }

                if (!dueDate) continue;
                if (!status || !status.toLowerCase().includes("done")) continue;

                const due = dayjs(dueDate).startOf("day");
                let completionStatus = "";
                let daysDelayed = 0;
                let daysBefore = 0;

                if (today.isAfter(due)) {
                  daysDelayed = today.diff(due, "day");
                  completionStatus = "Delayed";
                } else if (today.isSame(due)) {
                  completionStatus = "On Due Date";
                } else {
                  daysBefore = due.diff(today, "day");
                  completionStatus = "Before Due Date";
                }

                console.log(`Item ${item.id} → ${completionStatus}`);

                // === Update Completion Status ===
                try {
                  await client.request(UPDATE_SINGLE_SELECT, {
                    projectId,
                    itemId: item.id,
                    fieldId: completionStatusFieldId,
                    optionId: completionMap[completionStatus],
                  });
                  console.log(`Completion Status: ${completionStatus}`);
                } catch (err) {
                  console.error(`Failed to update Completion Status:`, err.response?.errors || err.message);
                }

                // === Update Days Delayed ===
                try {
                  await client.request(UPDATE_NUMBER, {
                    projectId,
                    itemId: item.id,
                    fieldId: daysDelayedFieldId,
                    number: daysDelayed,
                  });
                  console.log(`Days Delayed: ${daysDelayed}`);
                } catch (err) {
                  console.error(`Failed to update Days Delayed:`, err.response?.errors || err.message);
                }

                // === Update Days Before ===
                try {
                  await client.request(UPDATE_NUMBER, {
                    projectId,
                    itemId: item.id,
                    fieldId: daysBeforeFieldId,
                    number: daysBefore,
                  });
                  console.log(`Days Before: ${daysBefore}`);
                } catch (err) {
                  console.error(`Failed to update Days Before:`, err.response?.errors || err.message);
                }
              }

              console.log("All project items processed successfully!");
            } catch (err) {
              console.error("Error during execution:", err.response?.errors || err.message);
              process.exit(1);
            }
          })();
          EOF

          node script.js
